### ISSUE TITLE
2.5.1 breaks polymer 2.x apps

### ISSUE THREAD

**Issue by ankon** [firmfirm/f-jwt-decode#1]
So, it seems this project published 2.5.1 from the 2.5 branch recently, which has polymer 3.x support -- and drops polymer 2.x support.

Unfortunately this actually breaks old apps that used `bower install --save`, due to bower saving the dependency as `"f-jwt-decode": "firmfirm/f-jwt-decode#^2.0.2"` (in my case).

Instead of doing a minor update, could you re-consider and treat polymer 3.x as a major update instead?

**Comment by mkazlauskas** [comment]
I deleted the 2.5 tag and released it as 3.0.
